/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.felipe.mckyosk.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author felip
 */
public class CheckoutView extends javax.swing.JFrame {

    public JButton getBtbPlus() {
        return btbPlus;
    }

    public void setBtbPlus(JButton btbPlus) {
        this.btbPlus = btbPlus;
    }

    public JButton getBtnConfirmEdt() {
        return btnConfirmEdt;
    }

    public void setBtnConfirmEdt(JButton btnConfirmEdt) {
        this.btnConfirmEdt = btnConfirmEdt;
    }

    public JButton getBtnMinus() {
        return btnMinus;
    }

    public void setBtnMinus(JButton btnMinus) {
        this.btnMinus = btnMinus;
    }

    public JLabel getLblNumItem() {
        return lblNumItem;
    }

    public void setLblNumItem(JLabel lblNumItem) {
        this.lblNumItem = lblNumItem;
    }

    public JPanel getPnlEdt() {
        return pnlEdt;
    }

    public void setPnlEdt(JPanel pnlEdt) {
        this.pnlEdt = pnlEdt;
    }

    public JLabel getLblEdtItem() {
        return lblEdtItem;
    }

    public void setLblEdtItem(JLabel lblEdtItem) {
        this.lblEdtItem = lblEdtItem;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JLabel getLblTotal() {
        return lblTotal;
    }

    public void setLblTotal(JLabel lblTotal) {
        this.lblTotal = lblTotal;
    }

    public JList<String> getOrderList() {
        return orderList;
    }

    public void setOrderList(JList<String> orderList) {
        this.orderList = orderList;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public void setBtnEdit(JButton btnEdit) {
        this.btnEdit = btnEdit;
    }

    public JButton getBtnMainMenu() {
        return btnMainMenu;
    }

    public void setBtnMainMenu(JButton btnMainMenu) {
        this.btnMainMenu = btnMainMenu;
    }

    public JButton getBtnPay() {
        return btnPay;
    }

    public void setBtnPay(JButton btnPay) {
        this.btnPay = btnPay;
    }

    /**
     * Creates new form CheckoutView
     */
    public CheckoutView() {
        initComponents();
        orderList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList<>();
        btnPay = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        pnlEdt = new javax.swing.JPanel();
        btnMinus = new javax.swing.JButton();
        btbPlus = new javax.swing.JButton();
        lblNumItem = new javax.swing.JLabel();
        btnConfirmEdt = new javax.swing.JButton();
        lblEdtItem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orderList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(orderList);

        btnPay.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMainMenu.setText(" <- Main Menu");

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCancel.setText("Cancel Order");

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDelete.setText("Delete Selected Item");

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEdit.setText("Edit Quantity");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setText("Total: €0");

        btnMinus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMinus.setText("-");

        btbPlus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btbPlus.setText("+");

        lblNumItem.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumItem.setText("1");

        btnConfirmEdt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConfirmEdt.setText("Confirm Edition");

        lblEdtItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEdtItem.setText("Item Description");

        javax.swing.GroupLayout pnlEdtLayout = new javax.swing.GroupLayout(pnlEdt);
        pnlEdt.setLayout(pnlEdtLayout);
        pnlEdtLayout.setHorizontalGroup(
            pnlEdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEdtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmEdt)
                .addGap(43, 43, 43))
            .addGroup(pnlEdtLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lblEdtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(pnlEdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEdtLayout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(btnMinus)
                    .addGap(77, 77, 77)
                    .addComponent(lblNumItem)
                    .addGap(84, 84, 84)
                    .addComponent(btbPlus)
                    .addContainerGap(397, Short.MAX_VALUE)))
        );
        pnlEdtLayout.setVerticalGroup(
            pnlEdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEdtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEdtItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnConfirmEdt)
                .addGap(56, 56, 56))
            .addGroup(pnlEdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEdtLayout.createSequentialGroup()
                    .addContainerGap(129, Short.MAX_VALUE)
                    .addGroup(pnlEdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMinus)
                        .addComponent(btbPlus)
                        .addComponent(lblNumItem))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lblTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMainMenu)
                                .addGap(61, 61, 61)
                                .addComponent(btnCancel)
                                .addGap(76, 76, 76)
                                .addComponent(btnPay))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(pnlEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addGap(71, 71, 71)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(pnlEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(lblTotal)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay)
                    .addComponent(btnMainMenu)
                    .addComponent(btnCancel))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbPlus;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirmEdt;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdtItem;
    private javax.swing.JLabel lblNumItem;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> orderList;
    private javax.swing.JPanel pnlEdt;
    // End of variables declaration//GEN-END:variables
}
