/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.felipe.mckyosk.view;

import javax.swing.JLabel;

/**
 *
 * @author felip
 */
public class MainMenuView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryPanel = new javax.swing.JPanel();
        wNewBtn = new javax.swing.JButton();
        measlBtn = new javax.swing.JButton();
        burgersBtn = new javax.swing.JButton();
        milkShakeCDrinksBtn = new javax.swing.JButton();
        reducedPriceBtn = new javax.swing.JButton();
        mcCafeBtn = new javax.swing.JButton();
        wrapSaladsBtn = new javax.swing.JButton();
        vegetarianBtn = new javax.swing.JButton();
        friesSidesBtn = new javax.swing.JButton();
        desssertsBtn = new javax.swing.JButton();
        breakfastBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        centralMenuPanel = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoryPanel.setLayout(new java.awt.GridLayout(11, 0));

        wNewBtn.setText("What's New");
        categoryPanel.add(wNewBtn);

        measlBtn.setText("Meals");
        categoryPanel.add(measlBtn);

        burgersBtn.setText("Burgers");
        categoryPanel.add(burgersBtn);

        milkShakeCDrinksBtn.setText("Milkshakes & Cold Drinks");
        categoryPanel.add(milkShakeCDrinksBtn);

        reducedPriceBtn.setText("Reduced Price");
        categoryPanel.add(reducedPriceBtn);

        mcCafeBtn.setText("McCafé");
        categoryPanel.add(mcCafeBtn);

        wrapSaladsBtn.setText("Wraps and Salads");
        categoryPanel.add(wrapSaladsBtn);

        vegetarianBtn.setText("Vegetarian");
        categoryPanel.add(vegetarianBtn);

        friesSidesBtn.setText("Fries and Sides");
        categoryPanel.add(friesSidesBtn);

        desssertsBtn.setText("Desserts");
        categoryPanel.add(desssertsBtn);

        breakfastBtn.setText("Breakfast Menu");
        categoryPanel.add(breakfastBtn);

        jScrollPane1.setViewportView(categoryPanel);

        titleLabel.setText("Title");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 336, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        centralMenuPanel.setLayout(new java.awt.GridLayout(5, 4, 15, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(centralMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centralMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton breakfastBtn;
    private javax.swing.JButton burgersBtn;
    private javax.swing.JPanel categoryPanel;
    private javax.swing.JPanel centralMenuPanel;
    private javax.swing.JButton desssertsBtn;
    private javax.swing.JButton friesSidesBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mcCafeBtn;
    private javax.swing.JButton measlBtn;
    private javax.swing.JButton milkShakeCDrinksBtn;
    private javax.swing.JButton reducedPriceBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton vegetarianBtn;
    private javax.swing.JButton wNewBtn;
    private javax.swing.JButton wrapSaladsBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the breakfastBtn
     */
    public javax.swing.JButton getBreakfastBtn() {
        return breakfastBtn;
    }

    /**
     * @param breakfastBtn the breakfastBtn to set
     */
    public void setBreakfastBtn(javax.swing.JButton breakfastBtn) {
        this.breakfastBtn = breakfastBtn;
    }

    /**
     * @return the burgersBtn
     */
    public javax.swing.JButton getBurgersBtn() {
        return burgersBtn;
    }

    /**
     * @param burgersBtn the burgersBtn to set
     */
    public void setBurgersBtn(javax.swing.JButton burgersBtn) {
        this.burgersBtn = burgersBtn;
    }

    /**
     * @return the desssertsBtn
     */
    public javax.swing.JButton getDesssertsBtn() {
        return desssertsBtn;
    }

    /**
     * @param desssertsBtn the desssertsBtn to set
     */
    public void setDesssertsBtn(javax.swing.JButton desssertsBtn) {
        this.desssertsBtn = desssertsBtn;
    }

    /**
     * @return the friesSidesBtn
     */
    public javax.swing.JButton getFriesSidesBtn() {
        return friesSidesBtn;
    }

    /**
     * @param friesSidesBtn the friesSidesBtn to set
     */
    public void setFriesSidesBtn(javax.swing.JButton friesSidesBtn) {
        this.friesSidesBtn = friesSidesBtn;
    }

    /**
     * @return the mcCafeBtn
     */
    public javax.swing.JButton getMcCafeBtn() {
        return mcCafeBtn;
    }

    /**
     * @param mcCafeBtn the mcCafeBtn to set
     */
    public void setMcCafeBtn(javax.swing.JButton mcCafeBtn) {
        this.mcCafeBtn = mcCafeBtn;
    }

    /**
     * @return the measlBtn
     */
    public javax.swing.JButton getMeaslBtn() {
        return measlBtn;
    }

    /**
     * @param measlBtn the measlBtn to set
     */
    public void setMeaslBtn(javax.swing.JButton measlBtn) {
        this.measlBtn = measlBtn;
    }

    /**
     * @return the milkShakeCDrinksBtn
     */
    public javax.swing.JButton getMilkShakeCDrinksBtn() {
        return milkShakeCDrinksBtn;
    }

    /**
     * @param milkShakeCDrinksBtn the milkShakeCDrinksBtn to set
     */
    public void setMilkShakeCDrinksBtn(javax.swing.JButton milkShakeCDrinksBtn) {
        this.milkShakeCDrinksBtn = milkShakeCDrinksBtn;
    }

    /**
     * @return the reducedPriceBtn
     */
    public javax.swing.JButton getReducedPriceBtn() {
        return reducedPriceBtn;
    }

    /**
     * @param reducedPriceBtn the reducedPriceBtn to set
     */
    public void setReducedPriceBtn(javax.swing.JButton reducedPriceBtn) {
        this.reducedPriceBtn = reducedPriceBtn;
    }

    /**
     * @return the vegetarianBtn
     */
    public javax.swing.JButton getVegetarianBtn() {
        return vegetarianBtn;
    }

    /**
     * @param vegetarianBtn the vegetarianBtn to set
     */
    public void setVegetarianBtn(javax.swing.JButton vegetarianBtn) {
        this.vegetarianBtn = vegetarianBtn;
    }

    /**
     * @return the wNewBtn
     */
    public javax.swing.JButton getwNewBtn() {
        return wNewBtn;
    }

    /**
     * @param wNewBtn the wNewBtn to set
     */
    public void setwNewBtn(javax.swing.JButton wNewBtn) {
        this.wNewBtn = wNewBtn;
    }

    /**
     * @return the wrapSaladsBtn
     */
    public javax.swing.JButton getWrapSaladsBtn() {
        return wrapSaladsBtn;
    }

    /**
     * @param wrapSaladsBtn the wrapSaladsBtn to set
     */
    public void setWrapSaladsBtn(javax.swing.JButton wrapSaladsBtn) {
        this.wrapSaladsBtn = wrapSaladsBtn;
    }

    /**
     * @return the centralMenuPanel
     */
    public javax.swing.JPanel getCentralMenuPanel() {
        return centralMenuPanel;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    /**
     * @param centralMenuPanel the centralMenuPanel to set
     */
    public void setCentralMenuPanel(javax.swing.JPanel centralMenuPanel) {
        this.centralMenuPanel = centralMenuPanel;
    }
}
